spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath*:com/mall/user/dal/persistence/*Mapper.xml"
  type-aliases-package: com.mall.user.dal.entitys

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

verify:
  mail:
    subject: CSMALL用户激活邮件
    addresser: lucas_tung@yeah.net
    msg-prefix: http://localhost:8080/user/verify?uid=
